using BenchmarkDotNet.Running;
using CommandLine.Text;
using Microsoft.Diagnostics.Tracing.Stacks.Formats;
using OnlyForVerifiedGithubPublishers;
using StrideSourceGened;
using System.Buffers;
using System.Diagnostics;
using System.Text;
using VYaml.Emitter;
using VYaml.Parser;
using VYaml.Serialization;
new GeneratedYamlSerializerTInherit2<int>().Register();
new GeneratedYamlSerializerTInherit3().Register();
new GeneratedYamlSerializerTInherit().Register();
new GeneratedYamlSerializerNullSerialization().Register();
var b = new NullSerialization();
var s = YamlSerializer.SerializeToString(b);
File.WriteAllText("C:\\Godot\\tmp.yaml", s);
var w = "!{typeof(NullSerialization).FullName}\nGuid: !!null\n";
