using BenchmarkDotNet.Running;
using CommandLine.Text;
using Microsoft.Diagnostics.Tracing.Stacks.Formats;
using StrideSourceGened;
using System.Buffers;
using System.Diagnostics;
using System.Text;
using VYaml.Emitter;
using VYaml.Parser;
using VYaml.Serialization;
GeneratedYamlSerializerTInherit inherit3 = new GeneratedYamlSerializerTInherit();
GeneratedYamlSerializerTInherit2 inherit = new GeneratedYamlSerializerTInherit2();
GeneratedYamlSerializerTInherit3 inherit2 = new GeneratedYamlSerializerTInherit3();
inherit.Register();
inherit2.Register();

inherit3.Register();
var inh = new TInherit2();
var x2 = YamlSerializer.SerializeToString(inh);
File.WriteAllText("C:\\Godot\\tmp.yaml",x2);
var x = YamlSerializer.Deserialize<TInherit2>(File.ReadAllBytes("C:\\Godot\\tmp.yaml").AsMemory());
Console.Write(x.ToString());